# Generated by Django 6.1 on 2026-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=150, verbose_name='teléfono o correo')),
                ('sucursal', models.CharField(choices=[('delfines', 'Minimarket Los Delfines'), ('lobos', 'Minimarket Los Lobos 1838'), ('botilleria', 'Botillería Salas')], max_length=20)),
                ('mensaje', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de recepción')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-created'],
            },
        ),
    ]
