# Generated by Django 6.1 on 2026-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='sucursal',
            field=models.CharField(choices=[('delfines', 'Almacén Mis Reinas'), ('lobos', 'Minimarket Mis Reinas'), ('botilleria', 'Botillería Mis Reinas')], max_length=20),
        ),
    ]
