# Generated by Django 6.1 on 2026-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('categoria', models.CharField(choices=[('panaderia', 'Panadería'), ('abarrotes', 'Abarrotes'), ('bebidas', 'Bebidas'), ('mascotas', 'Mascotas'), ('servicios', 'Servicios')], max_length=20, verbose_name='categoría')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'producto o servicio',
                'verbose_name_plural': 'productos y servicios',
                'ordering': ['pk'],
            },
        ),
    ]
