# Generated by Django 6.1 on 2026-10-08 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(blank=True, help_text='Precio ficticio para el prototipo. Sin precio, el producto no se agrega al carrito.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='precio de ejemplo (CLP)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default='unidad', max_length=60, verbose_name='unidad de venta'),
        ),
    ]
